name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  opentofu:
    name: OpenTofu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.12.5

      - name: Setup Task
        uses: go-task/setup-task@v1

      - name: OpenTofu init
        run: tofu -chdir=hetzner-dokploy/terraform init -backend=false

      - name: OpenTofu check
        run: task dokploy:check
